# Create release versions with the creation of a release
name: Generate release-artifacts

# Only if a release is created
on:
  release:
    types: 
        - created

# Generate artifacts
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'aPing'
            compress: 'false'
            dest: 'dist'
